export const FETCH_LISTINGS_REQUEST = "FETCH_LISTINGS_REQUEST";
export const FETCH_LISTINGS_SUCCESS = "FETCH_LISTINGS_SUCCESS";
export const FETCH_LISTINGS_FAIL = "FETCH_LISTINGS_FAIL";

export const ACTIVE_MINING = "ACTIVE_MINING";
export const PASSIVE_MINING = "PASSIVE_MINING";
