export const FETCH_LISTINGS_REQUEST = "FETCH_LISTINGS_REQUEST";
export const FETCH_LISTINGS_SUCCESS = "FETCH_LISTINGS_SUCCESS";
export const FETCH_LISTINGS_FAIL = "FETCH_LISTINGS_FAIL";

export const ACTIVE_MINING = "ACTIVE_MINING";
export const PASSIVE_MINING = "PASSIVE_MINING";

export const ELECTRICITY_BILL = "ELECTRICITY_BILL";
export const UPDATE_POWER_COST = "UPDATE_POWER_COST";
export const UPDATE_POWER_RATE = "UPDATE_POWER_RATE";
export const UPDATE_POWER_WATTS = "UPDATE_POWER_WATTS";
